<a href="https://colab.research.google.com/github/somyaverma149/DSMP-learning/blob/main/session8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

np.sort

In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,100,15)

In [4]:
a

array([ 2, 90, 48, 77, 83, 24, 32, 83, 36, 15, 53, 84, 99,  6, 37])

In [5]:
b = np.random.randint(1,100,24).reshape(6,4)

In [6]:
b

array([[ 7, 16, 71, 57],
       [17, 90, 84, 94],
       [40, 41, 52, 72],
       [66,  8, 95,  8],
       [80, 34, 71,  8],
       [51, 90, 24, 27]])

In [7]:
np.sort(a)

array([ 2,  6, 15, 24, 32, 36, 37, 48, 53, 77, 83, 83, 84, 90, 99])

In [8]:
np.sort(b)

array([[ 7, 16, 57, 71],
       [17, 84, 90, 94],
       [40, 41, 52, 72],
       [ 8,  8, 66, 95],
       [ 8, 34, 71, 80],
       [24, 27, 51, 90]])

In [9]:
np.sort(b,axis=0)

array([[ 7,  8, 24,  8],
       [17, 16, 52,  8],
       [40, 34, 71, 27],
       [51, 41, 71, 57],
       [66, 90, 84, 72],
       [80, 90, 95, 94]])

In [10]:
np.sort(a)[::-1]

array([99, 90, 84, 83, 83, 77, 53, 48, 37, 36, 32, 24, 15,  6,  2])

In [11]:
# np.append
a

array([ 2, 90, 48, 77, 83, 24, 32, 83, 36, 15, 53, 84, 99,  6, 37])

In [12]:
np.append(a,20)

array([ 2, 90, 48, 77, 83, 24, 32, 83, 36, 15, 53, 84, 99,  6, 37, 20])

In [13]:
b

array([[ 7, 16, 71, 57],
       [17, 90, 84, 94],
       [40, 41, 52, 72],
       [66,  8, 95,  8],
       [80, 34, 71,  8],
       [51, 90, 24, 27]])

In [16]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[ 7., 16., 71., 57.,  1.],
       [17., 90., 84., 94.,  1.],
       [40., 41., 52., 72.,  1.],
       [66.,  8., 95.,  8.,  1.],
       [80., 34., 71.,  8.,  1.],
       [51., 90., 24., 27.,  1.]])

In [17]:
# np.concatenate
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

In [20]:
c


array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
d

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [24]:
# np.unique
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
e

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [25]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [26]:
# np.expand_dims
a

array([ 2, 90, 48, 77, 83, 24, 32, 83, 36, 15, 53, 84, 99,  6, 37])

In [29]:
np.expand_dims(a,axis=1)

array([[ 2],
       [90],
       [48],
       [77],
       [83],
       [24],
       [32],
       [83],
       [36],
       [15],
       [53],
       [84],
       [99],
       [ 6],
       [37]])

In [32]:
np.expand_dims(a,axis=0)

array([[ 2, 90, 48, 77, 83, 24, 32, 83, 36, 15, 53, 84, 99,  6, 37]])

In [33]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [34]:
# np.where
a

array([ 2, 90, 48, 77, 83, 24, 32, 83, 36, 15, 53, 84, 99,  6, 37])

In [38]:
np.where(a>50)

(array([ 1,  3,  4,  7, 10, 11, 12]),)

In [39]:
b

array([[ 7, 16, 71, 57],
       [17, 90, 84, 94],
       [40, 41, 52, 72],
       [66,  8, 95,  8],
       [80, 34, 71,  8],
       [51, 90, 24, 27]])

In [40]:
np.where(b<63)

(array([0, 0, 0, 1, 2, 2, 2, 3, 3, 4, 4, 5, 5, 5]),
 array([0, 1, 3, 0, 0, 1, 2, 1, 3, 1, 3, 0, 2, 3]))

In [42]:
# np.where(condition,true,false)
np.where(a>50,0,a)

array([ 2,  0, 48,  0,  0, 24, 32,  0, 36, 15,  0,  0,  0,  6, 37])

In [43]:
np.where(a%2==0,0,a)

array([ 0,  0,  0, 77, 83,  0,  0, 83,  0, 15, 53,  0, 99,  0, 37])

In [44]:
# np.argmax
a

array([ 2, 90, 48, 77, 83, 24, 32, 83, 36, 15, 53, 84, 99,  6, 37])

In [45]:
np.argmax(a)

np.int64(12)

In [48]:
b

array([[ 7, 16, 71, 57],
       [17, 90, 84, 94],
       [40, 41, 52, 72],
       [66,  8, 95,  8],
       [80, 34, 71,  8],
       [51, 90, 24, 27]])

In [47]:
np.argmax(b,axis=0)

array([4, 1, 3, 1])

In [49]:
np.argmax(b,axis=1)

array([2, 3, 3, 2, 0, 1])

In [50]:
np.argmin(a)

np.int64(0)

In [51]:
np.argmin(b,axis=0)

array([0, 3, 5, 3])

In [52]:
# np.cumsum
a

array([ 2, 90, 48, 77, 83, 24, 32, 83, 36, 15, 53, 84, 99,  6, 37])

In [53]:
np.cumsum(a)

array([  2,  92, 140, 217, 300, 324, 356, 439, 475, 490, 543, 627, 726,
       732, 769])

In [54]:
b

array([[ 7, 16, 71, 57],
       [17, 90, 84, 94],
       [40, 41, 52, 72],
       [66,  8, 95,  8],
       [80, 34, 71,  8],
       [51, 90, 24, 27]])

In [55]:
np.cumsum(b)

array([   7,   23,   94,  151,  168,  258,  342,  436,  476,  517,  569,
        641,  707,  715,  810,  818,  898,  932, 1003, 1011, 1062, 1152,
       1176, 1203])

In [56]:
e

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [57]:
np.cumsum(e)

array([ 1,  2,  4,  6,  9, 12, 16, 20, 25, 30, 36, 42])

In [58]:
np.cumsum(b,axis=0)

array([[  7,  16,  71,  57],
       [ 24, 106, 155, 151],
       [ 64, 147, 207, 223],
       [130, 155, 302, 231],
       [210, 189, 373, 239],
       [261, 279, 397, 266]])

In [59]:
np.cumsum(b,axis=1)

array([[  7,  23,  94, 151],
       [ 17, 107, 191, 285],
       [ 40,  81, 133, 205],
       [ 66,  74, 169, 177],
       [ 80, 114, 185, 193],
       [ 51, 141, 165, 192]])

In [60]:
np.cumprod(a)

array([                   2,                  180,                 8640,
                     665280,             55218240,           1325237760,
                42407608320,        3519831490560,      126713933660160,
           1900709004902400,   100737577259827200,  8461956489825484800,
        7630209175793172480,  8887766907339931648, -3194017755194458112])

In [61]:
np.cumprod(b,axis=0)

array([[          7,          16,          71,          57],
       [        119,        1440,        5964,        5358],
       [       4760,       59040,      310128,      385776],
       [     314160,      472320,    29462160,     3086208],
       [   25132800,    16058880,  2091813360,    24689664],
       [ 1281772800,  1445299200, 50203520640,   666620928]])

In [62]:
np.cumprod(b,axis=1)

array([[       7,      112,     7952,   453264],
       [      17,     1530,   128520, 12080880],
       [      40,     1640,    85280,  6140160],
       [      66,      528,    50160,   401280],
       [      80,     2720,   193120,  1544960],
       [      51,     4590,   110160,  2974320]])

In [63]:
np.cumprod(b)

array([                   7,                  112,                 7952,
                     453264,              7705488,            693493920,
                58253489280,        5475827992320,      219033119692800,
           8980357907404800,   466978611185049600, -3271028142095532032,
        5473071506209505280,  6891083902256939008,  9016928134574899200,
       -1651551218239012864, -2996888943154167808,  8786240375015604224,
       -3366231880016855040, -8483110966425288704, -8363545592370036736,
        3597403708788310016, -5896031357628317696,  6827850007421386752])

In [64]:
# np.percentile
a

array([ 2, 90, 48, 77, 83, 24, 32, 83, 36, 15, 53, 84, 99,  6, 37])

In [67]:
np.percentile(a,50)

np.float64(48.0)

In [68]:
b

array([[ 7, 16, 71, 57],
       [17, 90, 84, 94],
       [40, 41, 52, 72],
       [66,  8, 95,  8],
       [80, 34, 71,  8],
       [51, 90, 24, 27]])

In [70]:
np.percentile(a,100)

np.float64(99.0)

In [71]:
np.median(a)

np.float64(48.0)

In [72]:
np.mean(a)

np.float64(51.266666666666666)

In [73]:
# np.histogram(frequency count)
a

array([ 2, 90, 48, 77, 83, 24, 32, 83, 36, 15, 53, 84, 99,  6, 37])

In [76]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 1, 1, 3, 1, 1, 0, 1, 3, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [78]:
np.histogram(a,bins=[0,50,100])

(array([8, 7]), array([  0,  50, 100]))

In [79]:
# np.corrcoef(it return product moment correlation coefficient)
a

array([ 2, 90, 48, 77, 83, 24, 32, 83, 36, 15, 53, 84, 99,  6, 37])

In [80]:
np.corrcoef(a)

np.float64(1.0)

In [81]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [82]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [83]:
# np.isin
a

array([ 2, 90, 48, 77, 83, 24, 32, 83, 36, 15, 53, 84, 99,  6, 37])

In [85]:
items = [1,20,30,40,50,60,70,80,90,100]

np.isin(a,items)

array([False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [86]:
a[np.isin(a,items)]

array([90])

In [88]:
# np.flip
# (reverses the order of array elements along the specified axis,preserving the shape of the array)
a

array([ 2, 90, 48, 77, 83, 24, 32, 83, 36, 15, 53, 84, 99,  6, 37])

In [89]:
np.flip(a)

array([37,  6, 99, 84, 53, 15, 36, 83, 32, 24, 83, 77, 48, 90,  2])

In [90]:
b

array([[ 7, 16, 71, 57],
       [17, 90, 84, 94],
       [40, 41, 52, 72],
       [66,  8, 95,  8],
       [80, 34, 71,  8],
       [51, 90, 24, 27]])

In [93]:
np.flip(b)

array([[27, 24, 90, 51],
       [ 8, 71, 34, 80],
       [ 8, 95,  8, 66],
       [72, 52, 41, 40],
       [94, 84, 90, 17],
       [57, 71, 16,  7]])

In [94]:
np.flip(b,axis=0)

array([[51, 90, 24, 27],
       [80, 34, 71,  8],
       [66,  8, 95,  8],
       [40, 41, 52, 72],
       [17, 90, 84, 94],
       [ 7, 16, 71, 57]])

In [95]:
np.flip(b,axis=1)

array([[57, 71, 16,  7],
       [94, 84, 90, 17],
       [72, 52, 41, 40],
       [ 8, 95,  8, 66],
       [ 8, 71, 34, 80],
       [27, 24, 90, 51]])

In [97]:
# np.put(replace specific elements of an array with given values of p.array .Array indexed works on flattened array)
a

array([ 2, 90, 48, 77, 83, 24, 32, 83, 36, 15, 53, 84, 99,  6, 37])

In [98]:
np.put(a,[0,1],[110,530])

In [99]:
a

array([110, 530,  48,  77,  83,  24,  32,  83,  36,  15,  53,  84,  99,
         6,  37])

In [100]:
# np.delete
a

array([110, 530,  48,  77,  83,  24,  32,  83,  36,  15,  53,  84,  99,
         6,  37])

In [101]:
np.delete(a,0)

array([530,  48,  77,  83,  24,  32,  83,  36,  15,  53,  84,  99,   6,
        37])

In [102]:
np.delete(a,[4,6])

array([110, 530,  48,  77,  24,  83,  36,  15,  53,  84,  99,   6,  37])

Set functions


Set functions

In [103]:
# np.union1d
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [104]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [105]:
np.intersect1d(m,n)

array([3, 4, 5])

In [106]:
np.setdiff1d(m,n)

array([1, 2])

In [107]:
# remove common
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [108]:
# check items in given set
np.in1d(m,n)

/tmp/ipykernel_606/207282267.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,n)


array([False, False,  True,  True,  True])

In [109]:
m[np.in1d(m,1)]

/tmp/ipykernel_606/524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

In [111]:
# np.clip(used to limit the values in an array)
a

array([110, 530,  48,  77,  83,  24,  32,  83,  36,  15,  53,  84,  99,
         6,  37])

In [114]:
np.clip(a,a_min=6,a_max=99)

array([99, 99, 48, 77, 83, 24, 32, 83, 36, 15, 53, 84, 99,  6, 37])