<a href="https://colab.research.google.com/github/somyaverma149/DSMP-learning/blob/main/session6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating numpy Arrays

In [ ]:
# np.array
import numpy as np

a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
c1 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
# np.arange()
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [ ]:
# with reshape
np.arange(1,11).reshape(5,2)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
np.arange(16).reshape(2,2,2,2)


array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.random((3,4))

array([[0.24170867, 0.10953763, 0.8311658 , 0.21164729],
       [0.30223072, 0.89154317, 0.36050256, 0.85285616],
       [0.27261456, 0.3893834 , 0.52761222, 0.94252838]])

In [ ]:
# np.linspace  (lower range,upper range,no of itmes)
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
# np.identity (whose diagonal items id 1)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array attributes


In [ ]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


a1
a2
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# dimension ndim
a1.ndim


1

In [ ]:
a2.ndim

2

In [ ]:
a3.ndim

3

In [ ]:
# shape
a1.shape

(10,)

In [ ]:
a2.shape

(3, 4)

In [ ]:
# (2d array,no of rows,no of columns)
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size
a3.size

8

In [ ]:
a2.size

12

In [ ]:
print(a3.size)
a3

8


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# itemsize
a1.itemsize

8

In [ ]:
a2.itemsize

8

In [ ]:
print(a3.itemsize)
a3

8


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


Changing datatypes

In [ ]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# scalar operations
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
a1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
a1 / 2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [ ]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
a1 - 4

array([[-4, -3, -2, -1],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [ ]:
# relational opertor
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2 <5

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a2 > 26

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a2 <3

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a2 == 5

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a2 != 6

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2 >= 8

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2 <= 15

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
a1 + a2


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [ ]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [ ]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [ ]:
a1 - a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)

a1

array([[63., 55., 35.],
       [24., 39., 58.],
       [38., 25., 19.]])

In [ ]:
# max/min/sum/prod
np.max(a1)

np.float64(63.0)

In [ ]:
np.min(a1)

np.float64(19.0)

In [ ]:
np.sum(a1)

np.float64(356.0)

In [ ]:
np.prod(a1)

np.float64(118837178460000.0)

In [ ]:
np.max(a1,axis=0)

array([63., 55., 58.])

In [ ]:
# maen/median/std/var
np.mean(a1)


np.float64(39.55555555555556)

In [ ]:
np.median(a1)

np.float64(38.0)

In [ ]:
np.std(a1)

np.float64(15.011929412682369)

In [ ]:
np.var(a1)

np.float64(225.35802469135803)

Trigonometric function

In [ ]:
np.sin(a1)

array([[ 0.1673557 , -0.99975517, -0.42818267],
       [-0.90557836,  0.96379539,  0.99287265],
       [ 0.29636858, -0.13235175,  0.14987721]])

In [ ]:
np.cos(a1)

array([[ 0.98589658,  0.02212676, -0.90369221],
       [ 0.42417901,  0.26664293,  0.11918014],
       [ 0.95507364,  0.99120281,  0.98870462]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
np.log(a1)

array([[4.14313473, 4.00733319, 3.55534806],
       [3.17805383, 3.66356165, 4.06044301],
       [3.63758616, 3.21887582, 2.94443898]])

In [ ]:
np.exp(a1)

array([[2.29378316e+27, 7.69478527e+23, 1.58601345e+15],
       [2.64891221e+10, 8.65934004e+16, 1.54553894e+25],
       [3.18559318e+16, 7.20048993e+10, 1.78482301e+08]])

In [ ]:
# round/floor/ceil
np.round(np.random.random((2,3))*100)


array([[57.,  1., 15.],
       [18.,  3., 20.]])

In [ ]:
np.floor(np.random.random((2,3))*100)

array([[89., 99., 48.],
       [54., 15., 70.]])

In [ ]:
np.ceil(np.random.random((2,3))*100)

array([[ 1., 51., 19.],
       [90., 37., 36.]])

Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a1
a2
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a1[-1]

np.int64(9)

In [ ]:
a1[3]

np.int64(3)

In [ ]:
a1[0]

np.int64(0)

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,2]

np.int64(6)

In [ ]:
a2[2,3]

np.int64(11)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

np.int64(5)

In [ ]:
a3[0,0,0]

np.int64(0)

In [ ]:
a3[1,1,0]

np.int64(6)

In [ ]:
# slicing

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5]

array([2, 3, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
a2[0]

array([0, 1, 2, 3])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[2,:3]

array([ 8,  9, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[1:,0:3]

array([[ 4,  5,  6],
       [ 8,  9, 10]])

In [ ]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[2::2,1::2]

array([[ 9, 11]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

In [ ]:
a3[1,1:2]

array([[12, 13, 14]])

In [ ]:
a3[1,:1]

array([[ 9, 10, 11]])

In [ ]:
a3[1,:,1]

array([10, 13, 16])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[0:2,0:,::2]

array([[[ 0,  2],
        [ 3,  5],
        [ 6,  8]],

       [[ 9, 11],
        [12, 14],
        [15, 17]]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

Iterating

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [ ]:
# transpose
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
np.transpose(a3)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [ ]:
a3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [ ]:
# ravel
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.ravel(a2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking

In [ ]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

a4
a5


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [ ]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

a4
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# horizontal splitting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
# vertical splitting
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]